name: .NET Core

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Change Directory
      run: cd "ConsoleApp1/bin/Release/netcoreapp3.1"
    - name: Run
      run: dotnet ConsoleApp1.dll
    - name: Display
      run: type "Files\Home.md"
